/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running project. It is checked in here
// so the marketing-only Next.js migration has the expected type references.
